import time
print("Hello World!")
time.sleep(1)
print("Hello Again!")
time.sleep(1)
print("I like typing this.")
time.sleep(1)
print("This is fun.")
time.sleep(1)
print('Yay! Printing.')
time.sleep(1)
print("I'd much rather you 'not'.")
time.sleep(1)
print('I "said" not to touch this.')
